backend:
  # 必须使用 Git Gateway 或 GitHub/GitLab/Bitbucket 认证。
  name: github
  repo: PeixianChen/ChipChip_Bistro # 确保这里的用户名和仓库名正确
  branch: main 
  
# --- 核心配置：解决 CMS 启动错误 ---

# 解决 'media_library' 缺失的报错
media_library:
  # 使用 Netlify CMS 推荐的内置媒体库
  name: "cloudinary"
  config:
    # 这里的配置可以留空，只要声明了 media_library 即可满足要求
    # 即使您不使用 Cloudinary，这种配置模式也最能兼容 Decap 的最新要求
    
# 媒体文件的本地存储位置（相对于仓库根目录）
media_folder: "static/img" 
# 媒体文件在最终网站上的公开路径（相对于网站根目录）
public_folder: "/static/img"

# --- 核心配置结束 ---

locale: zh

collections:
  - name: "dishes" 
    label: "菜谱清单" 
    folder: "/" 
    extension: "json"
    format: "json" 
    files:
      - file: "dishes.json" 
        label: "所有菜品数据"
        name: "dish_data"
        fields:
          - name: "id"
            label: "唯一ID (请勿修改)"
            widget: "number"
            value_type: "int"
            min: 0
            required: true
            hint: "用于系统排序和区分，请勿随意更改"
          - name: "name"
            label: "菜名"
            widget: "string"
            required: true
          - name: "rating"
            label: "推荐等级 (1-5 星)"
            widget: "select"
            options: [5, 4, 3, 2, 1] 
            default: 5
            required: true
          - name: "link"
            label: "菜谱链接"
            widget: "string"
            required: false
            default: ""
            hint: "可选的外部食谱链接"
