backend:
  # 必须使用 Git Gateway 或 GitHub/GitLab/Bitbucket 认证。
  # 替换 YOUR_GITHUB_REPO_NAME 为你的仓库名 (例如: ChipChip_Bistro)
  name: github
  repo: PeixianChen/ChipChip_Bistro # 确保这里的用户名和仓库名正确
  branch: main # 你的主分支名称
  
# --- 新增的配置：解决 CMS 启动错误 ---
# 媒体文件的本地存储位置（相对于仓库根目录）
media_folder: "static/img" 
# 媒体文件在最终网站上的公开路径（相对于网站根目录）
public_folder: "/static/img"
# --- 新增配置结束 ---

# (可选) 设置管理界面语言为中文
locale: zh

# 定义 CMS 管理界面中的内容集合
collections:
  - name: "dishes" # 内部名称，用于 CMS 路由
    label: "菜谱清单" # 管理界面显示的名称
    folder: "/" # 指定内容文件所在的目录（即仓库根目录）
    extension: "json" # 文件的扩展名
    format: "json" # 文件格式为 JSON
    # 您的数据文件名为 dishes.json
    files:
      - file: "dishes.json" # CMS 要编辑的文件路径
        label: "所有菜品数据"
        name: "dish_data"
        # 定义 dishes.json 数组中的每一个对象（菜品）的字段
        fields:
          - name: "id"
            label: "唯一ID (请勿修改)"
            widget: "number"
            value_type: "int"
            min: 0
            required: true
            hint: "用于系统排序和区分，请勿随意更改"
          - name: "name"
            label: "菜名"
            widget: "string"
            required: true
          - name: "rating"
            label: "推荐等级 (1-5 星)"
            widget: "select"
            options: [5, 4, 3, 2, 1] # 评分选项
            default: 5
            required: true
          - name: "link"
            label: "菜谱链接"
            widget: "string"
            required: false
            default: ""
            hint: "可选的外部食谱链接"
